const state={datasets:[],filtered:[],visible:24,query:'',category:''};
const els={results:document.querySelector('#results'),search:document.querySelector('#search-input'),category:document.querySelector('#category-filter'),matches:document.querySelector('#match-count'),total:document.querySelector('#total-count'),more:document.querySelector('#load-more'),empty:document.querySelector('#empty-state'),dialog:document.querySelector('#detail-dialog'),dialogContent:document.querySelector('#dialog-content')};
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const validUrl=s=>/^https?:\/\//i.test(s||'');
const categoryClass=s=>['climate','environment','social','economic'].includes((s||'').toLowerCase())?(s||'').toLowerCase():'environment';
const searchable=d=>Object.values(d).join(' ').toLocaleLowerCase();

function optionize(select,values){[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b)).forEach(v=>select.add(new Option(v,v)))}
function mapTarget(d){return validUrl(d.interactiveUrl)?d.interactiveUrl:(validUrl(d.moreInfoUrl)?d.moreInfoUrl:'')}
function card(d){const target=mapTarget(d);return `<article class="dataset-card">
  ${target?`<a class="card-visual ${categoryClass(d.category)}" href="${esc(target)}" target="_blank" rel="noopener" aria-label="Open ${esc(d.name)} ${validUrl(d.interactiveUrl)?'interactive map':'dataset page'} in a new tab">`:`<div class="card-visual ${categoryClass(d.category)}">`}
    <img src="${esc(d.thumbnail)}" alt="Preview of ${esc(d.name)}" loading="lazy">${target?'<span class="visual-action" aria-hidden="true">↗</span>':''}
  ${target?'</a>':'</div>'}
  <div class="card-body"><div class="card-tags">${d.category?`<span class="tag">${esc(d.category)}</span>`:''}</div>
    <h3 class="dataset-title"><button type="button" data-detail="${d.id}">${esc(d.name)}</button></h3>
    <p class="card-description"><button type="button" data-detail="${d.id}" style="all:inherit;cursor:pointer;text-align:left">${esc(d.description)}</button></p>
    <div class="card-meta">${d.source?`<div class="meta-row"><span>Source</span><strong>${esc(d.source)}</strong></div>`:''}${d.timeframe?`<div class="meta-row"><span>Time</span><span>${esc(d.timeframe)}</span></div>`:''}</div>
  </div></article>`}

function apply(){const terms=state.query.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);state.filtered=state.datasets.filter(d=>terms.every(t=>searchable(d).includes(t))&&(!state.category||d.category===state.category));state.visible=24;render()}
function render(){els.matches.textContent=state.filtered.length;els.results.innerHTML=state.filtered.slice(0,state.visible).map(card).join('');els.empty.hidden=state.filtered.length>0;els.more.hidden=state.visible>=state.filtered.length;window.DATA_PRIMER_TRANSLATE?.refresh();}
function showDetail(id){const d=state.datasets.find(x=>x.id===Number(id));if(!d)return;const fields=[['Theme',d.category],['Source / provider',d.source],['Time period / year',d.timeframe],['Format / resolution',d.format]].filter(([,v])=>v);const links=[];if(validUrl(d.interactiveUrl))links.push(`<a href="${esc(d.interactiveUrl)}" target="_blank" rel="noopener">Explore Interactive Map ↗</a>`);if(validUrl(d.moreInfoUrl))links.push(`<a class="secondary" href="${esc(d.moreInfoUrl)}" target="_blank" rel="noopener">${esc(d.moreInfoLabel||'Access Dataset')} ↗</a>`);els.dialogContent.innerHTML=`<div class="detail-hero"><span class="tag">${esc(d.category||'Dataset')}</span><h2 id="detail-title">${esc(d.name)}</h2>${d.source?`<div class="detail-source">${esc(d.source)}</div>`:''}</div><div class="detail-body"><p class="detail-description">${esc(d.description)}</p>${fields.length?`<dl class="detail-list">${fields.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`:''}${links.length?`<div class="detail-links">${links.join('')}</div>`:''}</div>`;window.DATA_PRIMER_TRANSLATE?.refresh();els.dialog.showModal();history.replaceState(null,'',`#dataset-${d.id}`)}
function clearAll(){els.search.value='';els.category.value='';Object.assign(state,{query:'',category:''});apply();els.search.focus()}
async function init(){try{const res=await fetch('data/datasets.json');if(!res.ok)throw new Error('Dataset file could not be loaded');state.datasets=await res.json();state.filtered=state.datasets;els.total.textContent=state.datasets.length;optionize(els.category,state.datasets.map(d=>d.category));render();const match=location.hash.match(/^#dataset-(\d+)$/);if(match)showDetail(match[1])}catch(err){els.results.innerHTML=`<p class="empty-state">${esc(err.message)}. Please serve the site through a web server.</p>`}}
let timer;els.search.addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>{state.query=e.target.value;apply()},100)});els.category.addEventListener('change',e=>{state.category=e.target.value;apply()});document.querySelector('#clear-filters').addEventListener('click',clearAll);els.empty.querySelector('button').addEventListener('click',clearAll);els.more.addEventListener('click',()=>{state.visible+=24;render()});els.results.addEventListener('click',e=>{const btn=e.target.closest('[data-detail]');if(btn)showDetail(btn.dataset.detail)});document.querySelector('.dialog-close').addEventListener('click',()=>els.dialog.close());els.dialog.addEventListener('click',e=>{if(e.target===els.dialog)els.dialog.close()});els.dialog.addEventListener('close',()=>{if(location.hash.startsWith('#dataset-'))history.replaceState(null,'',location.pathname+location.search+'#explore')});document.addEventListener('keydown',e=>{if(e.key==='/'&&!/input|select|textarea/i.test(document.activeElement.tagName)){e.preventDefault();els.search.focus()}});init();
